### ISSUE TITLE
Option to hide fields only from input

### ISSUE THREAD

**Issue by mrBrownys** [adeyahya/prisma-typebox-generator#14]
Hi, thanks for the great job!

Is there an option to hide fields from input only?

@typebox.hide - hides from everywhere, perhaps I didn't notice it in the source code...

Thank you in advance!

**Comment by adeyahya** [comment]
Since I can't dedicate time to maintain this repository, I've updated the readme to refer to [prismabox](https://github.com/m1212e/prismabox) instead. This is because it offers better support, maintained, and has a more suitable name.
