### ISSUE TITLE
Customize import/export syntax

### ISSUE THREAD

**Issue by chimericdream** [adeyahya/prisma-typebox-generator#15]
My project is completely converted to using ESM, so imports without an extension are failing. It would be nice if there was a flag that changed the output along these lines:

```
// Before
export * from './SomeType';
export * from './SomeOtherType';
...
```

```
// After
export * from './SomeType.js';
export * from './SomeOtherType.js';
...
```

**Comment by adeyahya** [comment]
Since I can't dedicate time to maintain this repository, I've updated the readme to refer to [prismabox](https://github.com/m1212e/prismabox) instead. This is because it offers better support, maintained, and has a more suitable name.
