### ISSUE TITLE
Extended validation options

### ISSUE THREAD

**Issue by m1212e** [adeyahya/prisma-typebox-generator#18]
Is there a way to e.g. validate email inputs via the config object on the String validator?

```
const T = Type.String({
  format: 'email'
}) 
```

**Comment by adeyahya** [comment]
Since I can't dedicate time to maintain this repository, I've updated the readme to refer to [prismabox](https://github.com/m1212e/prismabox) instead. This is because it offers better support, maintained, and has a more suitable name.
