### ISSUE TITLE
Optional types in query results derive from typescript type

### ISSUE THREAD

**Issue by m1212e** [adeyahya/prisma-typebox-generator#19]
When I have this model
```
model AgendaItem {
  id           String         @id @default(uuid())
  title        String
  description  String?
}
```
with a generated schema like this:
```ts
export const AgendaItem = Type.Object(
  {
    id: Type.String(),
    title: Type.String(),
    description: Type.Optional(Type.String()),
  }
);
```
and I run a query like this:
```ts
await db.agendaItem.findMany();
```
the returned type is incompatible since the 
```ts
export type AgendaItemType = Static<typeof AgendaItem>;
```
expects the `description` field to be of type `string | undefined` but the query returns a type with a description of type `string | null` which makes sense from a DB perspective.

**Comment by crishoj** [comment]
@m1212e — have a look at the fork https://github.com/m1212e/prismabox. It generates types with `null` as expected.

**Comment by m1212e** [comment]
Hi, thanks for hinting me, although I'm quite familiar with the fork, since I wrote it :D

**Comment by adeyahya** [comment]
Since I can't dedicate time to maintain this repository, I've updated the readme to refer to [prismabox](https://github.com/m1212e/prismabox) instead. This is because it offers better support, maintained, and has a more suitable name.
